#               Translate
o_tab_translate=Isalin

#                 Google Translate
translator_GOOGLE=Google Translate
#                    Google 翻译
translator_GOOGLE_CN=Google 翻译
#               Microsoft Translator
translator_BING=Microsoft Translator
#                百度翻译 (Baidu Translator)
translator_BAIDU=百度翻译 (Baidu Translator)

#         Modal window
open_in_0=Modal window
#         Popup window
open_in_1=Popup window
#         New tab
open_in_2=Bagong tab
#         New window
open_in_3=Bagong window

#            Modal window
modal_window=Modal window
#                   Toolbar icon action
toolbar_icon_action=Pagkilos ng icon ng toolbar

#                    Translation provider
translation_provider=Tagapagbigay ng pagsasalin
#            Translate to:
translate_to=Isalin sa:
#          No overlay (the dark area around)
no_overlay=Walang overlay (ang madilim na lugar sa paligid)
#               Modal window will stay opened even if you click outside.
no_overlay_hint=Modal window ay mananatiling bukas kahit na mag-click ka sa labas.
#x                 Open translator in:
open_translator_in=
#                   Open translation in:
open_translation_in=Buksan ang pagsasalin sa:
#          Fallback method
fallback_1=Paraan ng fallback
#          Fallback method
fallback_2=Paraan ng fallback
#              Modal window and popup window can't be used in some cases.
fallback_title=Ang modal window at popup window ay hindi maaaring gamitin sa ilang mga kaso.
#           Open in new tab
open_in_tab=Buksan sa bagong tab

#                   Translate this page
translate_this_page=Isalin ang pahinang ito
#                   Translate "$1"
selection_translate=Isalin ang "$1"
#              Translate page
page_translate=Pahina ng isalin

#             selected text
selected_text=napiling teksto

#                    Disable context menu: "$1"
disable_context_menu=Huwag paganahin ang menu ng konteksto: "$1"



#        Web Translate
app_name=Web Translate
#        "Web Translate" is easy to use translator for your Web browser / Thunderbird!
app_desc=Ang "Web Translate" ay madaling gamitin na tagasalin para sa iyong Web browser / Thunderbird!


#               Import finished!
import_finished=Tapos na ang pag-import!
#            Error
import_error=Error
#                  Import backup file $1
import_backup_file=I-import ang backup na file na $1


#             Search
search_search=Maghanap


#        Homepage
homepage=Homepage
#          Addon page
addon_page=Pahina ng Addon


#               Font size
label_font_size=Laki ng font
#          Next
label_next=Susunod
#          Note:
label_note=Tandaan:
#            Remove
label_remove=Tanggalin
#             WARNING:
label_warning=BABALA:
#             Default:
label_default=Default:
#          Done!
label_done=Tapos na!
#            Copied!
label_copied=Kinopya!
#           Close
label_close=Isara
#               Open page
label_open_page=Buksan ang pahina


#           Agree
label_agree=Sang-ayon
#            Cancel
label_cancel=Kanselahin


#             Help this project
op_support_me=Tulungan ang proyektong ito
#                 Support independent developer!
support_developer=Suportahan ang independiyenteng developer!
#           Hello there!
hello_there=Kamusta diyan!
#        I'm addon developer since 2016 and my goal is to build powerful extensions for your web-browser to make you more productive.
about_me=Nag-develop ako ng addon mula pa noong 2016 at ang aking hangarin ay upang bumuo ng mga makapangyarihang extension para sa iyong web-browser upang mas maging produktibo ka.
#              If you think I'm doing a good job, please donate :)
about_good_job=Kung sa palagay mo ay mahusay ako sa trabaho, mangyaring mag-abuloy :)
#            Your donation is my only income!
about_income=Ang donasyon mo lang ang kita ko!
#            Thank you for supporting my work!
about_thanks=Salamat sa pagsuporta sa aking trabaho!

#                  Context menu
o_tab_context_menu=Menu ng konteksto
#           About
o_tab_about=Tungkol sa
#              Settings
o_tab_settings=Mga setting

#        pixels
o_pixels=mga pixel
#         seconds
o_seconds=segundo

#        or
label_or=o

#             Hello :)
o_about_hello=Kamusta :)
#             My name is Juraj Mäsiar and I'm the author of $1.
o_about_intro=Ang pangalan ko ay Juraj Mäsiar at ako ang may-akda ng $1.
#               If you like it, please rate it here:
o_about_like_it=Kung gusto mo ito, mangyaring i-rate ito dito:
#              Thank you!
o_about_thanks=Salamat!
#               Contact:
o_about_contact=Makipag-ugnay sa:
#              Report issues:
o_about_issues=Iulat ang mga isyu:
#                    Social media:
o_about_social_media=Social Media:

#             No matching results
ps_no_results=Walang tumutugma na mga resulta

#             No data
label_no_data=Walang data

#         Dark mode
dark_mode=Madilim na mode
#                Controlled by system
dark_mode_system=Kinokontrol ng system
