#               Translate
o_tab_translate=Preložiť

#                 Google Translate
translator_GOOGLE=Prekladač Google
#                    Google 翻译
translator_GOOGLE_CN=Google 翻译
#               Microsoft Translator
translator_BING=Microsoft Prekladač
#                DeepL Translator
translator_DEEPL=DeepL Translator
#                 Yandex Translate
translator_YANDEX=Yandex Translate
#                    Яндекс Переводчик
translator_YANDEX_RU=Яндекс Переводчик
#                百度翻译 (Baidu Translator)
translator_BAIDU=百度 翻译 (Baidu Prekladač)

#         Modal window
open_in_0=Modálne okno
#         Popup window
open_in_1=Vyskakovacie okno
#         New tab
open_in_2=Nová karta
#         New window
open_in_3=Nové okno

#            Modal window
modal_window=Modálne okno
#                   Toolbar icon action
toolbar_icon_action=Akcia ikony panela s nástrojmi

#            Sidebar size
sidebar_size=Veľkosť bočného panela

#                    Translation provider
translation_provider=Poskytovateľ prekladu
#            Translate to:
translate_to=Preložiť do:
#          No overlay (the dark area around)
no_overlay=Žiadne prekrytie (tmavá oblasť okolo)
#               Modal window will stay opened even if you click outside.
no_overlay_hint=Modálne okno zostane otvorené, aj keď kliknete von.
#x                 Open translator in:
open_translator_in=Otvoriť prekladač v:
#                   Open translation in:
open_translation_in=Otvoriť preklad v:
#          Fallback method
fallback_1=Záložná metóda
#          Fallback method
fallback_2=Záložná metóda
#              Modal window and popup window can't be used in some cases.
fallback_title=Modálne a vyskakovacie okno sa v niektorých prípadoch nedá použiť.
#           Open in new tab
open_in_tab=Otvoriť na novej karte

#                   Translate this page
translate_this_page=Preložiť túto stránku
#                   Translate "$1"
selection_translate=Preložiť "$1"
#              Translate page
page_translate=Preložiť stránku

#             selected text
selected_text=vybraný text

#                    Disable context menu: "$1"
disable_context_menu=Zakázať kontextové menu: "$1"



#        Web Translate
app_name=Web Translate
#        "Web Translate" is easy to use translator for your Web browser / Thunderbird!
app_desc=„Web Translate“ je ľahko použiteľný prekladač pre váš webový prehliadač / Thunderbird!


#               Import finished!
import_finished=Import dokočený
#            Error
import_error=Chyba
#                  Import backup file $1
import_backup_file=Importujte záložný súbor $1


#             Search
search_search=Hľadaj


#        Homepage
homepage=Domovská stránka
#          Addon page
addon_page=Stránka doplnku


#               Font size
label_font_size=Veľkosť textu
#          Next
label_next=Ďalej
#          Note:
label_note=Poznámka:
#            Remove
label_remove=Odstrániť
#             WARNING:
label_warning=POZOR:
#             Default:
label_default=Štandardné:
#          Done!
label_done=Hotovo!
#            Copied!
label_copied=Skopírované!
#           Close
label_close=Zavrieť
#               Open page
label_open_page=Otvoriť stránku


#           Agree
label_agree=Súhlasím
#            Cancel
label_cancel=Zrušiť


#             Help this project
op_support_me=Pomôž tomuto projektu
#                 Support independent developer!
support_developer=Podpor nezávislého vývojára!
#           Hello there!
hello_there=Ahoj!
#        I'm addon developer since 2016 and my goal is to build powerful extensions for your web-browser to make you more productive.
about_me=Som vývojár doplnkov od roku 2016 a mojím cieľom je vytvoriť výkonné rozšírenia pre Tvoj webový prehliadač, aby si dosiahol vyššiu produktivitu.
#              If you think I'm doing a good job, please donate :)
about_good_job=Ak si myslíš, že odvádzam dobrú prácu, prosím podpor ma :)
#            Your donation is my only income!
about_income=Tvoj dar je mojím jediným príjmom!
#            Thank you for supporting my work!
about_thanks=Ďakujem za podporu mojej práce!

#                  Context menu
o_tab_context_menu=Kontextové menu
#           About
o_tab_about=O rozšírení
#              Settings
o_tab_settings=Nastavenia

#        pixels
o_pixels=pixelov
#         seconds
o_seconds=sekúnd

#        or
label_or=alebo

#             Hello :)
o_about_hello=Ahoj :)
#             My name is Juraj Mäsiar and I'm the author of $1.
o_about_intro=Volám sa Juraj Mäsiar, som z Dolného Kubína a som autorom rozšírenia $1.
#               If you like it, please rate it here:
o_about_like_it=Ak sa ti páči, neváhaj a napíš mi hodnotenie tu:
#              Thank you!
o_about_thanks=Ďakujem!
#               Contact:
o_about_contact=Kontakt:
#              Report issues:
o_about_issues=Nahlásiť problémy:
#                    Social media:
o_about_social_media=Sociálne médiá:

#             No matching results
ps_no_results=Žiadne zodpovedajúce výsledky

#             No data
label_no_data=Žiadne dáta

#         Dark mode
dark_mode=Tmavý režim
#                Controlled by system
dark_mode_system=Ovládané systémom
